language: go

matrix:
  include:
    - os: linux
      sudo: required
      # just for demo
      python: 3.2
    - os: osx
      osx_image: xcode7.2

# just for demo
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi

script:
  - cd src
  - make all

go:
# - 1.7.1
  - master

install:
  - go get sort

script: go test ./...