language: go

os:
  - linux
  - osx

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

go:
  - 1.7
  - 1.8
  - 1.9
  - master

install:
  - go get -d -v ./...

script: go test ./http && go test ./datastructure